export class WorkshopRepository {
  constructor(db) { this.db = db; }
  async listActive() { const [rows] = await this.db.query(`SELECT id,name FROM workshops WHERE status='ACTIVE' AND active=1 ORDER BY name`); return rows; }
  async page({ page, limit, search, status }) { const clauses = ['1=1']; const params = []; if (search) { clauses.push('(name LIKE ? OR rfc LIKE ? OR legal_name LIKE ?)'); params.push(`%${search}%`, `%${search}%`, `%${search}%`); } if (status) { clauses.push('status=?'); params.push(status); } const where = clauses.join(' AND '); const [count] = await this.db.execute(`SELECT COUNT(*) total FROM workshops WHERE ${where}`, params); const [items] = await this.db.execute(`SELECT id,name,street,neighborhood,postal_code postalCode,state,municipality,locality,legal_name legalName,phone,rfc,contact_email contactEmail,photo_filename photoFilename,status FROM workshops WHERE ${where} ORDER BY name ASC LIMIT ? OFFSET ?`, [...params, limit, (page - 1) * limit]); return { items, pagination: { page, limit, total: count[0].total, pages: Math.ceil(count[0].total / limit) } }; }
  async findById(id) { const [rows] = await this.db.execute(`SELECT id,name,street,neighborhood,postal_code postalCode,state,municipality,locality,legal_name legalName,phone,rfc,contact_email contactEmail,photo_filename photoFilename,status FROM workshops WHERE id=?`, [id]); return rows[0] || null; }
  async findDuplicate({ rfc, legalName, name, street, postalCode }, excludedId = null) { const [rows] = await this.db.execute(`SELECT id FROM workshops WHERE (rfc=? OR legal_name=? OR (name=? AND street=? AND postal_code=?)) AND (? IS NULL OR id<>?) LIMIT 1`, [rfc, legalName, name, street, postalCode, excludedId, excludedId]); return rows[0] || null; }
  async create(workshop) { const [result] = await this.db.execute(`INSERT INTO workshops(name,street,neighborhood,postal_code,state,municipality,locality,legal_name,phone,rfc,contact_email,photo_filename,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`, [workshop.name,workshop.street,workshop.neighborhood,workshop.postalCode,workshop.state,workshop.municipality,workshop.locality,workshop.legalName,workshop.phone,workshop.rfc,workshop.contactEmail,workshop.photoFilename,workshop.status]); return result.insertId; }
  async update(id, workshop) { const photo = workshop.photoFilename ? ',photo_filename=?' : ''; const values = [workshop.name,workshop.street,workshop.neighborhood,workshop.postalCode,workshop.state,workshop.municipality,workshop.locality,workshop.legalName,workshop.phone,workshop.rfc,workshop.contactEmail,workshop.status]; if (workshop.photoFilename) values.push(workshop.photoFilename); values.push(id); const [result] = await this.db.execute(`UPDATE workshops SET name=?,street=?,neighborhood=?,postal_code=?,state=?,municipality=?,locality=?,legal_name=?,phone=?,rfc=?,contact_email=?,status=?${photo} WHERE id=?`, values); return result.affectedRows > 0; }
  async setStatus(id, status) { const [result] = await this.db.execute(`UPDATE workshops SET status=? WHERE id=?`, [status, id]); return result.affectedRows > 0; }
}
